name: Setup CI

description: Install Vite+ with node 24 and cache enabled and install dependencies.

runs:
  using: composite
  steps:
    - name: Setup Vite+
      uses: voidzero-dev/setup-vp@v1
      with:
        node-version: '24'
        cache: true
