name: Lint

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: CI setup
        uses: ./.github/actions/ci-setup

      - name: Build packages
        run: vp run build

      - name: Format and Lint
        run: vp check --fix

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: 'fix: auto-fix code style'
          commit_options: '--no-verify'
