name: Tests

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: CI setup
        uses: ./.github/actions/ci-setup

      - name: Build packages
        run: vp run build

      - name: Install Playwright Browsers
        run: vpx playwright install --with-deps chromium --only-shell

      - name: Run Tests
        run: vp run test

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: 'docs: update coverage badges'
          commit_options: '--no-verify'

      - name: Store Artifacts
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts
          path: |
            **/__screenshots__
          retention-days: 7
