name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: '24'
          cache: true

      - name: Get installed Playwright version
        id: playwright-version
        run: echo "VERSION=$(node -e "console.log(require('playwright/package.json').version)")" >> "$GITHUB_OUTPUT"

      - name: Restore Playwright cache
        uses: actions/cache@v6
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.VERSION }}'
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        run: vpx playwright install --with-deps chromium --only-shell

      - name: Run Tests
        run: vp run test

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'docs: update coverage badges'
          commit_options: '--no-verify'

      - name: Store Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: artifacts
          path: |
            **/__screenshots__
          retention-days: 7
