name: Tests

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: CI setup
        uses: ./.github/actions/ci-setup

      - name: Build packages
        run: vp run build

      - name: Install Playwright Browsers
        run: vpx playwright install --with-deps chromium --only-shell

      - name: Run Tests
        run: vp run test

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'docs: update coverage badges'
          commit_options: '--no-verify'

      - name: Store Artifacts
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: artifacts
          path: |
            **/__screenshots__
          retention-days: 7
